import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const openapiPath = join(__dirname, "..", "..", "openapi.json");

describe("openapi.json", () => {
  it("openapi.json exists (generated by build)", () => {
    expect(existsSync(openapiPath)).toBe(true);
  });

  it("is valid OpenAPI 3.0", () => {
    const spec = JSON.parse(readFileSync(openapiPath, "utf-8"));
    expect(spec.openapi).toBe("3.0.0");
  });

  it("has correct service info", () => {
    const spec = JSON.parse(readFileSync(openapiPath, "utf-8"));
    expect(spec.info.title).toBe("Chat Service");
    expect(spec.info.version).toBe("1.0.0");
  });

  it("documents GET /health", () => {
    const spec = JSON.parse(readFileSync(openapiPath, "utf-8"));
    expect(spec.paths["/health"]).toBeDefined();
    expect(spec.paths["/health"].get).toBeDefined();
    expect(spec.paths["/health"].get.responses["200"]).toBeDefined();
  });

  it("documents POST /chat with request body and responses", () => {
    const spec = JSON.parse(readFileSync(openapiPath, "utf-8"));
    const chat = spec.paths["/chat"]?.post;
    expect(chat).toBeDefined();
    expect(chat.requestBody.content["application/json"]).toBeDefined();
    expect(chat.responses["200"]).toBeDefined();
    expect(chat.responses["401"]).toBeDefined();
    expect(chat.responses["400"]).toBeDefined();
  });

  it("does not expose /openapi.json as a documented path", () => {
    const spec = JSON.parse(readFileSync(openapiPath, "utf-8"));
    expect(spec.paths["/openapi.json"]).toBeUndefined();
  });
});
